/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiexamples;

/**
 *
 * @author projava
 */
public class TestFrame extends java.awt.Frame {

    /**
     * Creates new form TestFrame
     */
    public TestFrame() {
        initComponents();
        setSize(500,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new java.awt.Label();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        c1 = new java.awt.Checkbox();
        c2 = new java.awt.Checkbox();
        c3 = new java.awt.Checkbox();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        ch = new java.awt.List();
        button7 = new java.awt.Button();
        ch1 = new java.awt.List();
        button8 = new java.awt.Button();
        t1 = new java.awt.TextField();
        button9 = new java.awt.Button();
        t2 = new java.awt.TextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        l1.setBackground(new java.awt.Color(204, 255, 204));
        l1.setText("On");
        add(l1);
        l1.setBounds(70, 40, 60, 50);

        button1.setLabel("Label");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(20, 150, 47, 24);

        button2.setLabel("Align");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(20, 190, 43, 24);

        button3.setLabel("0");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        add(button3);
        button3.setBounds(100, 150, 60, 24);

        c1.setLabel("Checkall");
        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });
        add(c1);
        c1.setBounds(20, 250, 74, 20);

        c2.setLabel("java");
        add(c2);
        c2.setBounds(20, 280, 84, 20);

        c3.setLabel("php");
        add(c3);
        c3.setBounds(20, 310, 84, 20);

        button4.setLabel("Add");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        add(button4);
        button4.setBounds(350, 50, 60, 24);

        button5.setLabel("Remove");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        add(button5);
        button5.setBounds(350, 90, 62, 24);

        button6.setLabel("Next");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        add(button6);
        button6.setBounds(350, 130, 40, 24);

        ch.setMultipleMode(true);
        add(ch);
        ch.setBounds(230, 70, 70, 80);

        button7.setLabel("Move");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        add(button7);
        button7.setBounds(350, 170, 44, 24);
        add(ch1);
        ch1.setBounds(230, 170, 70, 80);

        button8.setLabel("Multiple");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        add(button8);
        button8.setBounds(350, 220, 58, 24);
        add(t1);
        t1.setBounds(150, 300, 70, 20);

        button9.setLabel("Square");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        add(button9);
        button9.setBounds(230, 300, 56, 24);
        add(t2);
        t2.setBounds(310, 300, 60, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        String s=l1.getText();
        if(s.equalsIgnoreCase("on")){
            l1.setText("Off");
        }else{
            l1.setText("On");
        }
        
        
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        int n=l1.getAlignment();
        if(n==0){
            l1.setAlignment(2);
        }else{
            l1.setAlignment(0);
        }
        
        
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        String s=button3.getLabel();
        int n=Integer.parseInt(s);
        n++;
        button3.setLabel(""+n);
        
        
    }//GEN-LAST:event_button3ActionPerformed

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged
        boolean b=c1.getState();
        c2.setState(b);
        c3.setState(b);
        String s=c1.getLabel();
        if(s.equalsIgnoreCase("checkall")){
            c1.setLabel("uncheckall");
        }else{
            c1.setLabel("checkall");
        }
    }//GEN-LAST:event_c1ItemStateChanged

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        ch.add("agra"); ch.add("bhopal");
        ch.add("chennai"); ch.add("delhi");
        ch.add("mumbai"); ch.add("pune");
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        
        String s=ch.getSelectedItem();
        ch.remove(s);
        
        //int idx=ch.getItemCount()-1;
        //ch.remove(idx);
        
        //ch.remove("agra");
        //ch.remove(0);
        //ch.removeAll();
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        int n=ch.getSelectedIndex();
        ch.select(n+1);
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        String s[]=ch.getSelectedItems();
        for(String tmp:s){
            ch.remove(tmp);
            ch1.add(tmp);
        }
        
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        boolean b=ch.isMultipleMode();
        ch.setMultipleMode(!b);
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        String s=t1.getSelectedText();
        int n=Integer.parseInt(s);
        int res=n*n;
        t2.setText(""+res);
    }//GEN-LAST:event_button9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private java.awt.Checkbox c1;
    private java.awt.Checkbox c2;
    private java.awt.Checkbox c3;
    private java.awt.List ch;
    private java.awt.List ch1;
    private java.awt.Label l1;
    private java.awt.TextField t1;
    private java.awt.TextField t2;
    // End of variables declaration//GEN-END:variables
}
